[package]
name = "pochta"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "make"
path = "make.rs"

[dependencies]
tinyjson = "2.5.1"
base64 = "0.22.1"
rustyline = "16.0.0"
quoted_printable = "0.5.1"
